apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
- name: mysql-pass
  literals:
  - password=PASSWORD
resources:
  - mysql-secret.yaml
  - wordpress-pv-volume.yaml
  - wordpress-pvc.yaml
  - mysql-pv-volume.yaml
  - mysql-pvc.yaml
  - mysql-service.yaml
  - wordpress-service.yaml
  - mysql-deployment.yaml
  - wordpress-deployment.yaml
