apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql-headless-svc
  namespace: dev
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None